### ISSUE TITLE
Co jest do zrobienia?

### ISSUE THREAD

**Issue by adameus03** [adameus03/DES#1]
- Działanie funkcji zadeklarowanych w pliku des.h opiera się na  podstawowych działaniach kryptograficznych zdefiniowanych w pliku **_crypto.cpp_**, które są filarami algorytmu DES (`initial_perm`, `final_perm`, `e_selection`, `sbox_combined`, `p_permutation`, `permuted_choice_1`, `permuted_choice_2`, `xor_blks`, `lshift_blk7`).

- Wszystkie testy zadeklarowane w pliku **_tests.h_** dotyczące tych funkcji kończą się sukcesem.
- Jednak pojawiającym się problemem jest niespełnienie trzeciego warunku z listy TODO. 
- Do rozwiązania problemu może być pomocna poniższa lista, która sprowadza się do weryfikacji działania funkcji `feistel_f` oraz `encrypt`
## Todo!
- [x] Utworzenie większej liczby testów dla funkcji zadeklarowanych w pliku `crypto.h` (12.04.2023 - utworzono dla building-blocksów funkcji Feistel po dwa testy)
- [x]  Został napisany test `test_feistel_f` (w **_tests.cpp_**) dla funkcji `feistel_f` (z **_des.h_**) zwracający 0x1, gdy test przeszedł pomyślnie lub 0x0, gdy test zakończył się niepowodzeniem
- [x] Test `test_feistel_f` zakończył się pomyślnie
- [x] Podwójne zaszyfrowanie 64-bitowego bloku funkcją `encrypt` (**_des.h_**) z tym samym kluczem skutkuje wygenerowaniem oryginalnego bloku

**Comment by adameus03** [comment]
- [x] A może napisać więcej testów jednostkowych dla funkcji z pliku `crypto.cpp` ?
